name: main
on: 
  push:
    branches:
    - master

jobs:
  push:
    name: ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, latest]
    steps:
    - uses: actions/checkout@master

    - name: Build the docker container image
      working-directory: ./${{ matrix.node }}
      run: |
        docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` -t panascais/node:${{ matrix.node }} .
        docker tag panascais/node:${{ matrix.node }} docker.pkg.github.com/panascais-docker/node/main:${{ matrix.node }}

    - name: Push the image to the GitHub Registry
      run: |
        echo "${GITHUB_PACKAGE_REGISTRY_TOKEN}" | docker login docker.pkg.github.com -u publisher --password-stdin
        docker push docker.pkg.github.com/panascais-docker/node/main:${{ matrix.node }}
      env:
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}

    - name: Push the image to the Docker Registry
      run: |
        echo "${DOCKER_REGISTRY_TOKEN}" | docker login -u panascaisci --password-stdin
        docker push panascais/node:${{ matrix.node }}
      env:
        DOCKER_REGISTRY_TOKEN: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
