name: main
on: 
  push:
    branches:
    - master

jobs:
  push:
    name: ${{ matrix.node }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 15, 16, latest, lts]
    steps:
    - uses: actions/checkout@master

    - name: Install dependencies
      run: |
        sudo apt install jq -y

    - name: Build the docker container image
      working-directory: ./${{ matrix.node }}
      run: |
        docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` --build-arg NODE_VERSION=`cat ../configuration.json | jq '.versions."${{ matrix.node }}"' -r` --build-arg CHECKSUM=`cat ../configuration.json | jq '.checksums."${{ matrix.node }}"' -r` -t panascais/node:${{ matrix.node }} .
        docker tag panascais/node:${{ matrix.node }} docker.pkg.github.com/panascais-docker/node/node:${{ matrix.node }}
        docker tag panascais/node:${{ matrix.node }} quay.io/panascais/node:${{ matrix.node }}

    - name: Push the image to the GitHub Registry
      run: |
        echo "${GITHUB_PACKAGE_REGISTRY_TOKEN}" | docker login docker.pkg.github.com -u "${GITHUB_PACKAGE_REGISTRY_USERNAME}" --password-stdin
        docker push docker.pkg.github.com/panascais-docker/node/node:${{ matrix.node }}
      env:
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
        GITHUB_PACKAGE_REGISTRY_USERNAME: ${{ secrets.GITHUB_PACKAGE_REGISTRY_USERNAME }}

    - name: Push the image to the Docker Registry
      run: |
        echo "${DOCKER_REGISTRY_TOKEN}" | docker login -u "${DOCKER_REGISTRY_USERNAME}" --password-stdin
        docker push panascais/node:${{ matrix.node }}
      env:
        DOCKER_REGISTRY_TOKEN: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
        DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}

    - name: Push the image to the Quay Registry
      run: |
        echo "${QUAY_REGISTRY_TOKEN}" | docker login quay.io -u "${QUAY_REGISTRY_USERNAME}" --password-stdin
        docker push quay.io/panascais/node:${{ matrix.node }}
      env:
        QUAY_REGISTRY_TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}
        QUAY_REGISTRY_USERNAME: ${{ secrets.QUAY_REGISTRY_USERNAME }}
