name: main
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy-${{ matrix.node }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    timeout-minutes: 360
    strategy:
      matrix:
        # node: [8, 10, 12, 14, 15, 16, 17, 18, latest, lts]
        node: [16]
    steps:
      - name: pull repository
        id: repository
        uses: actions/checkout@master

      - name: install dependencies
        id: dependencies
        run: |
          sudo apt install jq -y

      - name: update repository
        id: update-repository
        run: |
          git pull origin master

      - name: build and push the docker container image
        id: build
        working-directory: ./${{ matrix.node }}
        run: |
          echo "${DOCKER_REGISTRY_TOKEN}" | docker login -u "${DOCKER_REGISTRY_USERNAME}" --password-stdin
          echo "${QUAY_REGISTRY_TOKEN}" | docker login quay.io -u "${QUAY_REGISTRY_USERNAME}" --password-stdin
          echo "${CONTAINER_REGISTRY_TOKEN}" | docker login ghcr.io -u "${CONTAINER_REGISTRY_USERNAME}" --password-stdin

          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7,linux/ppc64le,linux/s390x \
            --push \
            --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
            --build-arg VCS_REF=`git rev-parse --short HEAD` \
            -t panascais/node:${{ matrix.node }} \
            -t quay.io/panascais/node:${{ matrix.node }} \
            -t ghcr.io/panascais-docker/node/node:${{ matrix.node }} \
            .
        env:
          CONTAINER_REGISTRY_TOKEN: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
          CONTAINER_REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          DOCKER_REGISTRY_TOKEN: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
          DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          QUAY_REGISTRY_TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}
          QUAY_REGISTRY_USERNAME: ${{ secrets.QUAY_REGISTRY_USERNAME }}

  # notify-ci-node:
  #   name: notify-ci-node
  #   needs: [deploy, deploy-buildx-multiarch]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: start ci-node workflow
  #       id: push-ci-node
  #       run: |
  #         curl -XPOST -u "${{ secrets.PANASCAIS_CI_NODE_USERNAME}}:${{secrets.PANASCAIS_CI_NODE_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/panascais-docker/ci-node/actions/workflows/main.yml/dispatches --data '{"ref": "master"}';
