name: main
on: 
  push:
    branches:
    - master

jobs:
  node:8:
    name: Node 8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Build the docker container image
      working-directory: ./8
      run: |
        docker build -t panascais/node:8 .
        docker tag panascais/node:8 docker.pkg.github.com/panascais-docker/node:8

    - name: Push the image to the GitHub Registry
      run: |
        docker login docker.pkg.github.com -u publisher -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
        docker push docker.pkg.github.com/panascais-docker/node:8
      env:
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}

    - name: Push the image to the Docker Registry
      run: |
        docker login -u panascaisci -p "${DOCKER_REGISTRY_TOKEN}"
        docker push panascais-docker/node:8
      env:
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
